# Disable warnings
--no-warnings

# Extract audio
-x

# Extract to mp3
--audio-format mp3

# Chose the stream with the best audio
-f bestaudio

# Remove the any non-music parts
--sponsorblock-remove music_offtopic

# Overwrite any download files
--force-overwrites
